
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.SpinButton spinbuttonLv;
	private global::Gtk.HScrollbar hscrollbarLv;
	private global::Gtk.Label GtkLabel3;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Table table1;
	private global::Gtk.RadioButton radiobuttonLvType100;
	private global::Gtk.RadioButton radiobuttonLvType105;
	private global::Gtk.RadioButton radiobuttonLvType125;
	private global::Gtk.RadioButton radiobuttonLvType164;
	private global::Gtk.RadioButton radiobuttonLvType60;
	private global::Gtk.RadioButton radiobuttonLvType80;
	private global::Gtk.Label GtkLabel7;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label labelExp;
	private global::Gtk.Label GtkLabel8;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Pokeiken");
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.spinbuttonLv = new global::Gtk.SpinButton (1D, 100D, 1D);
		this.spinbuttonLv.CanFocus = true;
		this.spinbuttonLv.Name = "spinbuttonLv";
		this.spinbuttonLv.Adjustment.PageIncrement = 1D;
		this.spinbuttonLv.ClimbRate = 1D;
		this.spinbuttonLv.Numeric = true;
		this.spinbuttonLv.Value = 1D;
		this.hbox1.Add (this.spinbuttonLv);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.spinbuttonLv]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hscrollbarLv = new global::Gtk.HScrollbar (null);
		this.hscrollbarLv.Name = "hscrollbarLv";
		this.hscrollbarLv.Adjustment.Lower = 1D;
		this.hscrollbarLv.Adjustment.Upper = 120D;
		this.hscrollbarLv.Adjustment.PageIncrement = 10D;
		this.hscrollbarLv.Adjustment.PageSize = 20D;
		this.hscrollbarLv.Adjustment.StepIncrement = 10D;
		this.hscrollbarLv.Adjustment.Value = 1D;
		this.hbox1.Add (this.hscrollbarLv);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hscrollbarLv]));
		w2.Position = 1;
		this.GtkAlignment1.Add (this.hbox1);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>目標レベル</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel3;
		this.vbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.radiobuttonLvType100 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("100万"));
		this.radiobuttonLvType100.CanFocus = true;
		this.radiobuttonLvType100.Name = "radiobuttonLvType100";
		this.radiobuttonLvType100.DrawIndicator = true;
		this.radiobuttonLvType100.UseUnderline = true;
		this.radiobuttonLvType100.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.table1.Add (this.radiobuttonLvType100);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobuttonLvType100]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobuttonLvType105 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("105万"));
		this.radiobuttonLvType105.CanFocus = true;
		this.radiobuttonLvType105.Name = "radiobuttonLvType105";
		this.radiobuttonLvType105.DrawIndicator = true;
		this.radiobuttonLvType105.UseUnderline = true;
		this.radiobuttonLvType105.Group = this.radiobuttonLvType100.Group;
		this.table1.Add (this.radiobuttonLvType105);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobuttonLvType105]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobuttonLvType125 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("125万"));
		this.radiobuttonLvType125.CanFocus = true;
		this.radiobuttonLvType125.Name = "radiobuttonLvType125";
		this.radiobuttonLvType125.DrawIndicator = true;
		this.radiobuttonLvType125.UseUnderline = true;
		this.radiobuttonLvType125.Group = this.radiobuttonLvType100.Group;
		this.table1.Add (this.radiobuttonLvType125);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobuttonLvType125]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobuttonLvType164 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("164万"));
		this.radiobuttonLvType164.CanFocus = true;
		this.radiobuttonLvType164.Name = "radiobuttonLvType164";
		this.radiobuttonLvType164.DrawIndicator = true;
		this.radiobuttonLvType164.UseUnderline = true;
		this.radiobuttonLvType164.Group = this.radiobuttonLvType100.Group;
		this.table1.Add (this.radiobuttonLvType164);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobuttonLvType164]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobuttonLvType60 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("60万"));
		this.radiobuttonLvType60.CanFocus = true;
		this.radiobuttonLvType60.Name = "radiobuttonLvType60";
		this.radiobuttonLvType60.DrawIndicator = true;
		this.radiobuttonLvType60.UseUnderline = true;
		this.radiobuttonLvType60.Group = this.radiobuttonLvType100.Group;
		this.table1.Add (this.radiobuttonLvType60);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobuttonLvType60]));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobuttonLvType80 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("80万"));
		this.radiobuttonLvType80.CanFocus = true;
		this.radiobuttonLvType80.Name = "radiobuttonLvType80";
		this.radiobuttonLvType80.DrawIndicator = true;
		this.radiobuttonLvType80.UseUnderline = true;
		this.radiobuttonLvType80.Group = this.radiobuttonLvType100.Group;
		this.table1.Add (this.radiobuttonLvType80);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobuttonLvType80]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table1);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>レベルタイプ</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel7;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.labelExp = new global::Gtk.Label ();
		this.labelExp.Name = "labelExp";
		this.labelExp.LabelProp = global::Mono.Unix.Catalog.GetString ("123,456,789Exp");
		this.labelExp.Selectable = true;
		this.hbox2.Add (this.labelExp);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labelExp]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		this.GtkAlignment2.Add (this.hbox2);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>必要な経験値</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel8;
		this.vbox1.Add (this.frame3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame3]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 192;
		this.DefaultHeight = 184;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.spinbuttonLv.ValueChanged += new global::System.EventHandler (this.OnSpinbuttonLvValueChanged);
		this.hscrollbarLv.ValueChanged += new global::System.EventHandler (this.OnHscrollbarLvValueChanged);
		this.radiobuttonLvType100.GroupChanged += new global::System.EventHandler (this.OnRadiobuttonLvType100GroupChanged);
	}
}
